# Generated by Django 4.2.14 on 2024-07-29 09:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_image_alter_category_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("author_name", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
